// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnzudunkcgbnmipshadn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduenVkdW5rY2dibm1pcHNoYWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MzkzMjgsImV4cCI6MjA1ODAxNTMyOH0.MgHVkrkG34-0G24g70n4MhS-f7z4DNalqrBy-fSvyQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);